test:
  database:
    adapter: sqlite
    database: <%= Playa::Root %>/db/test.db
  library: <%= Playa::Root %>/test/fixtures

development:
  database:
    adapter: sqlite
    database: <%= Playa::Root %>/db/development.db
    logger: _stderr_
  library: <%= ENV['HOME'] %>/Music
